### PR TITLE
Update Graphql Version

### PR DESCRIPTION
**Pull request by estrada9166**
#135, #136

### CODE REVIEW

**Comment by AmrAnwar** [comment]
it'll be really nice updating to the new version as I'm getting errors in compiling the schema and thanks

**Comment by tatejones** [comment]
Hi @estrada9166, is there a schedule or any outstanding issues for this pull request to be completed?  Cheers

**Comment by iamacook** [comment]
Would be great to see this implemented @estrada9166. This is now becoming a big issue for us.

**Comment by estrada9166** [comment]
There's a new version publish with this change!

**Pull request merged**
